title: Portfólio de André Pires
description: Este espaço foi criado para organizar e compartilhar meus cursos, estudos, projetos práticos e resenhas de livros, servindo como uma plataforma para praticar e validar meus conhecimentos na área de segurança da informação, com ênfase em segurança ofensiva (Red Team).
show_downloads: false
google_analytics:
theme: jekyll-theme-hacker
